services:
  stremioaddonwrapper:
    image: kirkspock97/addonwrapperdb:latest
    container_name: stremioaddonwrapper
    ports:
      - "7005:7005"  # Expose port 7000 for external access
    volumes:
      - ./streams.db:/usr/src/app/streams.db  # Mount the database file
      - ./data:/data                         # Optional: Volume to persist other data
    env_file:
      - .env                                 # Load environment variables from .env
    restart: unless-stopped
